on:
  push:
    branches: main
  pull_request:

name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  ci-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add rustup components
        run: rustup component add rustfmt && rustup component add clippy
      - name: Setup build cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-run
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Deny all clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
